name: functions

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '**.bicep'
      - '.github/workflows/infra.yml'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.11'

jobs:
  deploy-function:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4
      
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
            
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        with:
          app-name: dreamtrackerfunctions
          package: .
          scm-do-build-during-deployment: true
          enable-oryx-build: true 