name: infra

on:
  push:
    paths:
    - '**.bicep'
    - .github/workflows/bicep.yml
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Create Resource Group if it doesn''t exist'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            if [ $(az group exists --name dreamtracker) = false ]; then
              az group create --name dreamtracker --location northeurope
            fi

      - name: 'Deploy Azure Infrastructure with Bicep'
        uses: azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          resourceGroupName: dreamtracker
          template: './bicep/main.bicep'
          deploymentName: 'dreamtracker-${{ github.run_number }}'
          parameters: >
            googleEmail=${{ vars.GOOGLEEMAIL }}
            googlePassword=${{ secrets.GOOGLEPASSWORD }}


      - name: 'Get Function App Publish Profile'
        uses: azure/CLI@v1
        id: get-publish-profile
        with:
          inlineScript: |
            FUNCTION_APP_NAME=$(az functionapp list --resource-group dreamtracker --query "[0].name" --output tsv)
            echo "::set-output name=functionAppName::$FUNCTION_APP_NAME"
            PUBLISH_PROFILE=$(az functionapp deployment list-publishing-profiles --name $FUNCTION_APP_NAME --resource-group dreamtracker --xml)
            echo "::add-mask::$PUBLISH_PROFILE"
            echo "::set-output name=publishProfile::$PUBLISH_PROFILE"

      - name: 'Save Publish Profile as GitHub Secret'
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ steps.get-publish-profile.outputs.functionAppName }}
          app-settings-json: '[{ "name": "AZURE_FUNCTIONAPP_PUBLISH_PROFILE", "value": "${{ steps.get-publish-profile.outputs.publishProfile }}" }]' 