name: infra

on:
  push:
    paths:
    - '**.bicep'
    - .github/workflows/infra.yml
  workflow_dispatch:

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Create Resource Group if it doesn''t exist'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            if [ $(az group exists --name dreamtracker) = false ]; then
              az group create --name dreamtracker --location northeurope
            fi

      - name: 'Deploy Azure Infrastructure with Bicep'
        uses: azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          resourceGroupName: dreamtracker
          template: './bicep/main.bicep'
          deploymentName: 'dreamtracker-${{ github.run_number }}'
          parameters: |
            googleEmail=${{ secrets.GOOGLEEMAIL }}
            googlePassword=${{ secrets.GOOGLEPASSWORD }}
            openaiKey=${{ secrets.OPENAI_API_KEY }}
            excludedTags=${{ vars.EXCLUDED_TAGS }}
            dreamAnalyzerPrompt=${{ vars.DREAM_ANALYZER_PROMPT }}

      - name: 'Get Function App Publish Profile'
        uses: azure/CLI@v1
        id: get-publish-profile
        with:
          inlineScript: |
            FUNCTION_APP_NAME=$(az functionapp list --resource-group dreamtracker --query "[0].name" --output tsv)
            echo "functionAppName=$FUNCTION_APP_NAME" >> $GITHUB_OUTPUT
            PUBLISH_PROFILE=$(az functionapp deployment list-publishing-profiles --name $FUNCTION_APP_NAME --resource-group dreamtracker --xml)
            echo "::add-mask::$PUBLISH_PROFILE"
            echo "publishProfile=$PUBLISH_PROFILE" >> $GITHUB_OUTPUT

      - name: 'Save Publish Profile as Repository Secret'
        env:
          PUBLISH_PROFILE: ${{ steps.get-publish-profile.outputs.publishProfile }}
          FUNCTION_APP_NAME: ${{ steps.get-publish-profile.outputs.functionAppName }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            # Store publish profile in Function App Settings
            az functionapp config appsettings set --name $FUNCTION_APP_NAME \
                                                 --resource-group dreamtracker \
                                                 --settings AZURE_FUNCTIONAPP_PUBLISH_PROFILE="$PUBLISH_PROFILE"
            
            echo "Function App publish profile saved as app setting for future deployments" 